from .hanmatek import PZA_DEVICES_LIST as HANMATEK_DEVICES
from .panduza import PZA_DEVICES_LIST as PANDUZA_DEVICES
from .ftdi import PZA_DEVICES_LIST as FTDI_DEVICES
from .servomotor import PZA_DEVICES_LIST as SERVOMOTOR_DEVICES

PZA_DEVICES_LIST = [] \
    + HANMATEK_DEVICES \
    + PANDUZA_DEVICES \
    + FTDI_DEVICES \
    + SERVOMOTOR_DEVICES
